const allCandlesData = [
  [
    { id: "m0", participating: true, active: false },
    { id: "m1", participating: true, active: false },
    { id: "m2", participating: true, active: false },
    { id: "m3", participating: true, active: true },
    { id: "m4", participating: true, active: true },
    { id: "m5", participating: true, active: false },
    { id: "m6", participating: true, active: true },
    { id: "m7", participating: true, active: true },
  ],
  [
    { id: "m0", participating: true, active: true },
    { id: "m1", participating: true, active: false },
    { id: "m2", participating: true, active: false },
    { id: "m3", participating: true, active: true },
    { id: "m4", participating: true, active: true },
    { id: "m5", participating: true, active: true },
    { id: "m6", participating: true, active: true },
    { id: "m7", participating: true, active: false },
  ],
  [
    { id: "m0", participating: true, active: false },
    { id: "m1", participating: true, active: true },
    { id: "m2", participating: true, active: false },
    { id: "m3", participating: true, active: false },
    { id: "m4", participating: true, active: true },
    { id: "m5", participating: true, active: false },
    { id: "m6", participating: true, active: true },
    { id: "m7", participating: true, active: false },
  ],
  [
    { id: "m0", participating: true, active: true },
    { id: "m1", participating: true, active: true },
    { id: "m2", participating: true, active: false },
    { id: "m3", participating: true, active: false },
    { id: "m4", participating: true, active: false },
    { id: "m5", participating: true, active: true },
    { id: "m6", participating: true, active: true },
    { id: "m7", participating: true, active: true },
  ],
  [
    { id: "m0", participating: true, active: true },
    { id: "m1", participating: true, active: true },
    { id: "m2", participating: true, active: true },
    { id: "m3", participating: true, active: false },
    { id: "m4", participating: true, active: true },
    { id: "m5", participating: true, active: true },
    { id: "m6", participating: true, active: true },
    { id: "m7", participating: true, active: true },
  ],
  [
    { id: "m0", participating: true, active: false },
    { id: "m1", participating: true, active: false },
    { id: "m2", participating: true, active: false },
    { id: "m3", participating: true, active: false },
    { id: "m4", participating: true, active: true },
    { id: "m5", participating: true, active: true },
    { id: "m6", participating: true, active: false },
    { id: "m7", participating: true, active: true },
  ],
  [
    { id: "m0", participating: true, active: false },
    { id: "m1", participating: true, active: false },
    { id: "m2", participating: true, active: true },
    { id: "m3", participating: true, active: false },
    { id: "m4", participating: true, active: true },
    { id: "m5", participating: true, active: false },
    { id: "m6", participating: true, active: false },
    { id: "m7", participating: true, active: true },
  ],
  [
    { id: "m0", participating: true, active: true },
    { id: "m1", participating: true, active: false },
    { id: "m2", participating: true, active: true },
    { id: "m3", participating: true, active: true },
    { id: "m4", participating: true, active: true },
    { id: "m5", participating: true, active: true },
    { id: "m6", participating: true, active: false },
    { id: "m7", participating: true, active: true },
  ],
  [
    { id: "m0", participating: true, active: true },
    { id: "m1", participating: true, active: false },
    { id: "m2", participating: true, active: true },
    { id: "m3", participating: true, active: false },
    { id: "m4", participating: true, active: false },
    { id: "m5", participating: true, active: true },
    { id: "m6", participating: true, active: false },
    { id: "m7", participating: true, active: true },
  ],
  [
    { id: "m0", participating: true, active: true },
    { id: "m1", participating: true, active: false },
    { id: "m2", participating: true, active: true },
    { id: "m3", participating: true, active: true },
    { id: "m4", participating: true, active: true },
    { id: "m5", participating: false, active: false },
    { id: "m6", participating: false, active: false },
    { id: "m7", participating: false, active: false },
  ],
];

export default allCandlesData;
